#!/bin/bash
if [ "$1" == "" ] || [ $# -gt 1 ]; then
        echo "Usage: ./get-states <teamId>" 1>&2
	exit 1
fi
node . "workflowStates({first: 250, after: after})" "r.nodes.filter(e => e._team.id === $1).map(n => n.name + ' | ' + n.id)"

